config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tops#home'
  get 'privacy', to: 'tops#privacy'
  get 'uses', to: 'tops#uses'
  get 'line', to: 'tops#line'
  get 'index', to: 'tops#index'

  # ユーザーのパスには:nameが入るようにしてあります
  resources :users, param: :name, only: %i[new create index destroy] do
    resources :followers, only: [:index]

    get 'following', to: 'users#following'
    get 'follower', to: 'users#follower'

    resources :diaries
  end

  resources :relationships, only: %i[create destroy]

  resources :bookmarks, only: %i[create destroy]

  # profiles_path, edit_profiles_path
  resource :profiles, only: %i[show edit update]

  # login_path
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  # logout_path
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'search', to: 'users#search'

  # linebot
  post '/callback', to: 'linebot#callback'

  resources :password_resets, only: %i[new create edit update]

  resources :contacts, only: %i[new create]

  post 'guest', to: 'guest_sessions#create'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # Followerクラスという存在しないクラスを参照することを防ぎ、Userクラスであることを明示。
  belongs_to :follower, class_name: 'User'
  belongs_to :user
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォローする
  def create
    # パラメータでfollowerのnameを取得
    @other_user = User.find_by(name: params[:follower])
    # 現在ログインしているユーザーが@other_userをフォローする
    current_user.follow(@other_user)
  end

  # フォローを外す
  def destroy
    # 現在ログインしているユーザーのフォロー情報をrelationshipsテーブルのfollower_idから取得
    @user = current_user.relationships.find(params[:id]).follower
    # 現在ログインしているユーザーがフォローを外す
    current_user.unfollow(params[:id])
  end
end

app/views/relationships/_follow_button.html.erb
<%= link_to t('defaults.follow'),
              relationships_path(follower: user),
              class: "btn btn-sm follow-button",
              method: :post,
              id: "js-follow-button-#{user.id}",
              remote: true %>

app/views/relationships/_follow_button_area.html.erb
<% if current_user.following?(user) %>
  <%= render 'relationships/unfollow_button', { user: user } %>
<% else %>
  <%= render 'relationships/follow_button', { user: user } %>
<% end %>

app/views/relationships/_follow_count_area.html.erb
<div class="text-center">
  <%= render 'relationships/following_count', { user: user } %>
  <p class="follow-count">フォロー中</p>
</div>
💛 
<div class="text-center">
  <%= render 'relationships/follower_count', { user: user } %>
  <p class="follow-count">フォロワー</p>
</div>

app/views/relationships/_follower_count.html.erb
<%= link_to user.followers.count, user_follower_path(user.name), class: "result-link", id: "followers" %>

app/views/relationships/_following_count.html.erb
<%= link_to user.followings.count, user_following_path(user.name), class: "result-link" %>

app/views/relationships/_unfollow_button.html.erb
<%= link_to t('defaults.unfollow'),
              relationship_path(current_user.relationships.find_by(follower: user)),
              class: "btn btn-sm unfollow-button",
              method: :delete,
              id: "js-follow-button-#{user.id}",
              remote: true %>

app/views/relationships/create.js.erb
$("#js-follow-button-<%= @other_user.id %>").replaceWith("<%= j(render 'unfollow_button', user: @other_user) %>");
$("#followers").html('<%= @other_user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#js-follow-button-<%= @user.id %>").replaceWith("<%= j(render 'follow_button', user: @user) %>");
$("#followers").html('<%= @user.followers.count %>');