config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tops#home'
  get 'privacy', to: 'tops#privacy'
  get 'uses', to: 'tops#uses'
  get 'line', to: 'tops#line'
  get 'index', to: 'tops#index'

  # ユーザーのパスには:nameが入るようにしてあります
  resources :users, param: :name, only: %i[new create index destroy] do
    resources :followers, only: [:index]

    get 'following', to: 'users#following'
    get 'follower', to: 'users#follower'

    resources :diaries
  end

  resources :relationships, only: %i[create destroy]

  resources :bookmarks, only: %i[create destroy]

  # profiles_path, edit_profiles_path
  resource :profiles, only: %i[show edit update]

  # login_path
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  # logout_path
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'search', to: 'users#search'

  # linebot
  post '/callback', to: 'linebot#callback'

  resources :password_resets, only: %i[new create edit update]

  resources :contacts, only: %i[new create]

  post 'guest', to: 'guest_sessions#create'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  # トップページにアクセスする前にrequire_loginを行わない
  skip_before_action :require_login, only: %i[home privacy uses index]

  def home; end

  def privacy; end

  def uses; end

  def line; end

  def index
    @diaries = Diary.all
  end
end

app/views/tops/_line.html.erb
<div class="container">
  <div class="col-12 text-center line-modal">
    <div class="row justify-content-end line-close">
      <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
        <span aria-hidden="true">&times; close</span>
      </button>
    </div>
      <h3 class="line-title">LINEで公式アカウントを友達に追加</h3>
      <img src="<%= asset_pack_path 'media/images/qrcode.png' %>" class="qr-image">
      <p class="line-body">
        毎日夜9:00にリマインドを受け取ることができます。<br>
        日記のつけ忘れを防ぎましょう！
      </p>
    </div>
  </div>
</div>

app/views/tops/home.html.erb
<% content_for(:title) %>

<div class='top-wrapper'>
  <div class="col-12 home">
    <div class="row justify-content-center">
      <% if !logged_in? %>
        <% if !logged_in? || (current_user.color == "pink") %>
          <img src="<%= asset_pack_path 'media/images/emory_top.jpg' %>" class="top-image">
        <% else %>
          <img src="<%= asset_pack_path 'media/images/emory_top_blue.jpg' %>" class="top-image" >
        <% end %>

        <div class="d-flex align-items-center text-center">
          <div class="text-center">
            <p class="top-letter">絵文字だけで日記をつけて
            <br>友達とシェアしませんか？</p>
            <div class="">
              <%= button_to t('defaults.login'), login_path, method: :get, class:'btn btn-normal' %>
            </div>
            <div class="">
              <%= button_to t('defaults.register'), new_user_path, method: :get, class:'btn btn-normal' %>
            </div>
            <div class="">
              <%= button_to 'guest login', guest_path, method: :post, class:'btn btn-normal' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="text-center">
          <% if !logged_in? || (current_user.color == "pink") %>
            <img src="<%= asset_pack_path 'media/images/emory_top.jpg' %>" class="top-image">
          <% else %>
            <img src="<%= asset_pack_path 'media/images/emory_top_blue.jpg' %>" class="top-image" >
          <% end %>
        </div>
        <div class="d-flex align-items-center text-center">
          <div class="text-center">
            <p class="top-letter">絵文字だけで日記をつけて
            <br>友達とシェアしませんか？</p>
            <div class="">
              <%= button_to t('defaults.mine'), user_diaries_path(current_user), method: :get, class:'btn btn-normal' %>
            </div>
            <div class="">
              <%= button_to t('defaults.logout'), logout_path, method: :delete, data: { confirm: "<i class='fa fa-exclamation-circle'></i>
              ログアウトしますか?", commit: 'logout', cancel: 'cancel' }, class:'btn btn-normal' %>
            </div>
          </div>
        </div>
        <%= link_to "write diary", new_user_diary_path(current_user.name), class: "btn-circle-border" %>
      <% end %>
    </div>
    <div class="row justify-content-center text-center">
      <div class="col-11 card-deck top-card">
        <div class="card">
          <div class="card-body">
            <p class="top-letter">カレンダーの色とグラフをみたら
            <br>感情の変化が一目でわかる！
            <br>疲れた日が続いていることにスグ気がつけるよ。</p>
            <img src="<%= asset_pack_path 'media/images/top-calendar.png' %>" class="top-image1">
          </div>
        </div>

        <div class="card">
          <div class="card-body">
            <p class="top-letter">友達の日記をのぞき見👀
            <br>絵文字だけで書かれた日記を見て、
            <br>友達の1日がどんな1日だったのか想像してみてね。</p>
            <img src="<%= asset_pack_path 'media/images/top-show.png' %>" class="top-image1">
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/tops/index.html.erb
<% content_for(:title, 'everyone diary') %>

<div class="container">
  <div class="row justify-content-center">
    <div class="friend-calendar col-12 col-md-8">
    <p class="text-center top-calendar">気になる絵文字をクリックしてみてください。<br>日記を書いたユーザーのページをみることができます。</p>
      <%= week_calendar events: @diaries do |date, diaries| %>
        <%= date %>
      
        <% diaries.shuffle.first(7).each do |diary| %>
          <% @user = diary.user %>
          <div class="feeling text-center" %>
            <%= link_to diary.feeling, user_diaries_path(@user), id: "emoji-feeling-top-#{diary.score}", class: "feeling-link" %>
          </div>
        <% end %>
      <% end %>
      <div class="text-center">
      <%= button_to 'back', root_path, method: :get, class:'btn btn-normal' %>
      </div>
    </div>
  </div>
</div>

app/views/tops/line.js.erb
$("#lineModal").html("<%= j(render 'line') %>");
$("#lineModal").show();

app/views/tops/privacy.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
<div class="row justify-content-center">
  <div class="col-12">
    <div class="document">
    <h1 class="text-center">プライバシーポリシー</h1>
    <h3>お客様から取得する情報</h3>
      当社は、お客様から以下の情報を取得します。<br>
      <ul>
      <li>氏名(ニックネームやペンネームも含む)</li>
      <li>メールアドレス</li>
      <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
      <li>Cookie(クッキー)を用いて生成された識別情報</li>
      <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
      <li>当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴</li>
      <li>当社アプリの起動時間、入力履歴、購買履歴等の当社アプリの利用履歴</li>
      <li>お客様の位置情報</li>
      </ul>
    <h3>お客様の情報を利用する目的</h3>
      当社は、お客様から取得した情報を、以下の目的のために利用します。<br>
      <ul>
      <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
      <li>お客様の当社サービスの利用履歴を管理するため</li>
      <li>利用料金の決済のため</li>
      <li>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</li>
      <li>市場分析、マーケティングのため</li>
      <li>当社のサービスに関するご案内をするため</li>
      <li>お客様からのお問い合わせに対応するため</li>
      <li>当社の規約や法令に違反する行為に対応するため</li>
      <li>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
      <li>当社規約の変更等を通知するため</li>
      <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
      </ul>
      <h3>第三者提供</h3>
      当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。<br>
      但し、次の場合は除きます。<br>
      <ul>
      <li>個人データの取扱いを外部に委託する場合</li>
      <li>当社や当社サービスが買収された場合</li>
      <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
      <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
      <h3>アクセス解析ツール</h3>
      当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。<br>
　    <%= link_to 'https://marketingplatform.google.com/about/analytics/terms/jp/', 'https://marketingplatform.google.com/about/analytics/terms/jp/', class: "copylight-link" %><br>
      <h3>プライバシーポリシーの変更</h3>
      当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。<br>
      <h3>お問い合わせ</h3>
      お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、<%= link_to 'お問い合わせフォーム', new_contact_path, class: "copylight-link" %>よりご連絡ください。<br>
      この場合、必ず、運転免許証のご提示等当社が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。<br><br>
        <div class="text-right">
          事業者の名称<br>
          emory<br>
          2021年07月16日 制定<br>
          2021年07月21日 改定<br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tops/uses.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
<div class="row justify-content-center">
  <div class="col-12">
    <div class="document">
    <h1 class="text-center">利用規約</h1>
    この利用規約（以下，「本規約」といいます。）は，emory（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。<br>
    登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。<br>
      
    <h3>第1条（適用）</h3>
      <ul>
      <li>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
      <li>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
      <li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
      </ul>

    <h3>第2条（利用登録）</h3>
      <ul>
      <li>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</li>
      <li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</li>
        <ul>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
        </ul>
      </ul>

      <h3>第3条（ユーザーIDおよびパスワードの管理）</h3>
      <ul>
      <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
      <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
      <li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
      </ul>

      <h3>第4条（利用料金および支払方法）</h3>
      <ul>
      <li>ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
      <li>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
      </ul>

      <h3>第5条（禁止事項）</h3>
      ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。<br>
      <ul>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
      <li>当社，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
      <li>本サービスによって得られた情報を商業的に利用する行為</li>
      <li>当社のサービスの運営を妨害するおそれのある行為</li>
      <li>不正アクセスをし，またはこれを試みる行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>不正な目的を持って本サービスを利用する行為</li>
      <li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>当社が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
      <li>面識のない異性との出会いを目的とした行為</li>
      <li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>その他，当社が不適切と判断する行為</li>
      </ul>

      <h3>第6条（本サービスの提供の停止等）</h3>
      <ul>
      <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
        <ul>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他，当社が本サービスの提供が困難と判断した場合</li>
        </ul>
      <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li> 
      </ul>

      <h3>第7条（利用制限および登録抹消）</h3>
      <ul>
      <li>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</li>
        <ul>
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>料金等の支払債務の不履行があった場合</li>
        <li>当社からの連絡に対し，一定期間返答がない場合</li>
        <li>本サービスについて，最終の利用から一定期間利用がない場合</li>
        <li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
        </ul>
      <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li> 
      </ul>

      <h3>第8条（退会）</h3>
      ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。<br>

      <h3>第9条（保証の否認および免責事項）</h3>
      <ul>
      <li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
      <li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
      <li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
      <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
      </ul>

      <h3>第10条（サービス内容の変更等）</h3>
      当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。<br>      

      <h3>第11条（利用規約の変更）</h3>
      当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。<br>      

      <h3>第12条（個人情報の取扱い）</h3>
      当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。<br>

      <h3>第13条（通知または連絡）</h3>
      ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。<br>

      <h3>第14条（権利義務の譲渡の禁止）</h3>
      ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。<br>

      <h3>第15条（準拠法・裁判管轄）</h3>
      <ul>
      <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
      <li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
      </ul>
        <div class="text-right">
        以上
        </div>
      </div>
    </div>
  </div>
</div>