config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tops#home'
  get 'privacy', to: 'tops#privacy'
  get 'uses', to: 'tops#uses'
  get 'line', to: 'tops#line'
  get 'index', to: 'tops#index'

  # ユーザーのパスには:nameが入るようにしてあります
  resources :users, param: :name, only: %i[new create index destroy] do
    resources :followers, only: [:index]

    get 'following', to: 'users#following'
    get 'follower', to: 'users#follower'

    resources :diaries
  end

  resources :relationships, only: %i[create destroy]

  resources :bookmarks, only: %i[create destroy]

  # profiles_path, edit_profiles_path
  resource :profiles, only: %i[show edit update]

  # login_path
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  # logout_path
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'search', to: 'users#search'

  # linebot
  post '/callback', to: 'linebot#callback'

  resources :password_resets, only: %i[new create edit update]

  resources :contacts, only: %i[new create]

  post 'guest', to: 'guest_sessions#create'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  # sorceryのメソッド。Userモデルで必要なクラスメソッドとインスタンスメソッドを得ることができる。
  authenticates_with_sorcery!

  # Diaryモデルとのアソシエーション、ユーザーが消されたら日記も消す
  has_many :diaries, dependent: :destroy

  # Relationshipモデルとのアソシエーション、ユーザーが消されたらフォロー情報も消す
  has_many :relationships, dependent: :destroy
  # following=フォローしている人を取得する、relationshipモデルのfollowerを参照する
  has_many :followings, through: :relationships, source: :follower

  # passive_relationshipsは別名。follower_idを入り口にして、class_name: 'Relationship'をつけて参照モデルを指定。
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # Userはたくさんのfollowersをpassive_relationshipsを通じて持っている。relationshipのuserを参照する
  has_many :followers, through: :passive_relationships, source: :user

  # 各ユーザーはたくさんブックマークをすることが出来る
  has_many :bookmarks, dependent: :destroy
  # お気に入りにしている日記を取得する
  has_many :bookmark_diaries, through: :bookmarks, source: :diary

  # パスワードは半角英数字数字のみ可能。
  VALID_PASSWORD_REGEX = /\A[a-zA-Z0-9]+\z/.freeze

  # if~内容変更時パスワードの入力を省略させることが出来る。パスワードの長さは8文字以上。
  validates :password, length: { minimum: 8 }, format: { with: VALID_PASSWORD_REGEX, message: '半角英数字のみ使用できます' }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  # emailのバリデーション
  # コールバック。emailをセーブする前に全て小文字にする
  before_save { self.email = email.downcase }
  # emailの形式になっていてる確認する。@や.など必須項目があるか確認する
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  # emailは必須条件、一意であることを確認するときに大文字小文字の区別をしている
  validates :email, { presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } }

  # nicknameは必須項目、絵文字だけ受け取る、絵文字1文字だけ許可
  validates :nickname, presence: true, emoji: true, a_emoji_nickname: true

  # nameはTwitterでいうユーザーIDのようなもの。一意で必須項目。15文字以内。半角英数字のみ。
  validates :name, uniqueness: true, presence: true, length: { maximum: 15 }, format: { with: /\A[a-zA-Z0-9]+\z/, message: '半角英数字のみ使用できます' }

  enum role: { general: 0, admin: 1 }

  # サイトのテーマカラー
  enum color: { pink: 0, blue: 1 }

  # フォローする
  def follow(other_user)
    # 自分自身はフォローできない
    return if self == other_user

    relationships.find_or_create_by!(follower: other_user)
  end

  # フォローしているか確認する
  def following?(user)
    followings.include?(user)
  end

  # 　フォローをはずす
  def unfollow(relathinoship_id)
    relationships.find(relathinoship_id).destroy!
  end

  # ブックマークする
  def bookmark(diary)
    bookmark_diaries << diary
  end

  # ブックマークを外す
  def unbookmark(diary)
    bookmark_diaries.delete(diary)
  end

  # ブックマークしているか判定するメソッド
  def bookmark?(diary)
    bookmark_diaries.include?(diary)
  end

  # nicknameに使うランダム絵文字
  def emoji_nickname
    ["\u{1F47B}", "\u{1F47E}", "\u{1F916}", "\u{1F63A}", "\u{1F440}", "\u{1F9DA}", "\u{1F9DB}", "\u{1F9DC}", "\u{1F9DE}", "\u{1F483}", "\u{1F57A}", "\u{1F435}", "\u{1F412}", "\u{1F98D}", "\u{1F436}", "\u{1F415}", "\u{1F429}", "\u{1F43A}", "\u{1F98A}", "\u{1F99D}", "\u{1F431}", "\u{1F408}", "\u{1F981}", "\u{1F42F}", "\u{1F405}", "\u{1F406}", "\u{1F434}",
     "\u{1F40E}", "\u{1F984}", "\u{1F993}", "\u{1F98C}", "\u{1F42E}", "\u{1F404}", "\u{1F437}", "\u{1F416}", "\u{1F417}", "\u{1F40F}", "\u{1F411}", "\u{1F47B}", "\u{1F42A}", "\u{1F999}", "\u{1F992}", "\u{1F418}", "\u{1F98F}", "\u{1F42D}", "\u{1F401}", "\u{1F400}", "\u{1F439}", "\u{1F430}", "\u{1F407}", "\u{1F43F}", "\u{1F9AB}", "\u{1F994}", "\u{1F987}",
     "\u{1F43B}", "\u{1F428}", "\u{1F43C}", "\u{1F9A5}", "\u{1F9A6}", "\u{1F9A8}", "\u{1F998}", "\u{1F9A1}", "\u{1F43E}", "\u{1F983}", "\u{1F414}", "\u{1F413}", "\u{1F423}", "\u{1F424}", "\u{1F425}", "\u{1F426}", "\u{1F427}", "\u{1F54A}", "\u{1F985}", "\u{1F986}", "\u{1F9A2}", "\u{1F989}", "\u{1F9A4}", "\u{1FAB6}", "\u{1F9A9}", "\u{1F99A}", "\u{1F99C}",
     "\u{1F438}", "\u{1F40A}", "\u{1F422}", "\u{1F98E}", "\u{1F40D}", "\u{1F432}", "\u{1F409}", "\u{1F995}", "\u{1F996}", "\u{1F433}", "\u{1F40B}", "\u{1F42C}", "\u{1F9AD}", "\u{1F41F}", "\u{1F420}", "\u{1F421}", "\u{1F988}", "\u{1F419}", "\u{1F41A}", "\u{1F40C}", "\u{1F98B}", "\u{1F41B}", "\u{1F41C}", "\u{1F41D}", "\u{1F41E}", "\u{1F490}", "\u{1F338}",
     "\u{1F339}", "\u{1F33A}", "\u{1F33B}", "\u{1F33C}", "\u{1F337}", "\u{1F331}", "\u{1FAB4}", "\u{1F332}", "\u{1F333}", "\u{1F334}", "\u{1F335}", "\u{1F33E}", "\u{1F33F}", "\u{1F340}", "\u{1F341}", "\u{1F342}", "\u{1F343}", "\u{1F347}", "\u{1F348}", "\u{1F349}", "\u{1F34A}", "\u{1F34B}", "\u{1F34C}", "\u{1F34D}", "\u{1F96D}", "\u{1F34E}", "\u{1F34F}",
     "\u{1F350}", "\u{1F351}", "\u{1F352}", "\u{1F353}", "\u{1FAD0}", "\u{1F95D}", "\u{1F345}", "\u{1F965}", "\u{1F951}", "\u{1F346}", "\u{1F955}", "\u{1F33D}", "\u{1F344}", "\u{1F95C}", "\u{1F330}", "\u{1F96F}", "\u{1F95E}", "\u{1F9C0}", "\u{1F356}", "\u{1F357}", "\u{1F354}", "\u{1F35F}", "\u{1F355}", "\u{1F32D}", "\u{1F96A}", "\u{1F37F}", "\u{1F96B}",
     "\u{1F359}", "\u{1F362}", "\u{1F360}", "\u{1F363}", "\u{1F364}", "\u{1F365}", "\u{1F361}", "\u{1F980}", "\u{1F99E}", "\u{1F990}", "\u{1F366}", "\u{1F367}", "\u{1F368}", "\u{1F369}", "\u{1F370}", "\u{1F9C1}", "\u{1F36B}", "\u{1F36C}", "\u{1F36D}", "\u{1F36E}", "\u{1F36F}", "\u{1F37C}", "\u{1F9C3}", "\u{1F3D5}", "\u{1F30B}", "\u{1F3D6}", "\u{1F3DC}",
     "\u{1F3DD}", "\u{1F3DF}", "\u{1F3A0}", "\u{1F3A1}", "\u{1F6FC}", "\u{1FA82}", "\u{1F681}", "\u{1F680}", "\u{1FA90}", "\u{1F384}", "\u{1F383}", "\u{1F380}", "\u{1F3A3}", "\u{1F3BF}", "\u{1FA81}", "\u{1F9F8}", "\u{1FA86}", "\u{1F3A8}", "\u{1F9F5}", "\u{1FA70}", "\u{1F48E}", "\u{1F941}", "\u{1F516}", "\u{1F3F9}"].sample
  end

  def to_param
    name
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.hex(10)
      user.password_confirmation = user.password
      user.name = 'guest'
      user.nickname = "\u{1F530}"
    end
  end

  def self.other_user
    find_or_create_by!(email: 'guest2@example.com') do |user|
      user.password = SecureRandom.hex(10)
      user.password_confirmation = user.password
      user.name = 'guest2'
      user.nickname = "\u{1F351}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # new, createアクション(新規作成)の前にrequire_loginを行わない
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[following follower]

  # pagyを導入
  include Pagy::Backend

  # ransackを使って検索したユーザーを@qに入れている
  # ユーザー検索ページ
  def index
    if current_user.name == 'guest'
      redirect_to user_diaries_path(current_user), danger: t('.fail')
    else
      @q = User.ransack(params[:q])
    end
  end

  # 新規作成したユーザー
  def new
    @user = User.new
    redirect_to user_diaries_path(current_user.name), danger: t('.fail') if current_user
  end

  # 新規作成するユーザー情報
  def create
    @user = User.new(user_params)
    @user.nickname = @user.emoji_nickname
    if @user.save
      auto_login(@user)
      redirect_to new_user_diary_path(@user), success: t('.success')
    else
      render :new
    end
  end

  # 退会
  def destroy
    # 　@user = User.find(params[:id])
    # userのnemeをパラメータで取得してユーザーを指定する
    if current_user.name == 'guest'
      redirect_to profiles_path, danger: t('.fail')
    else
      @user = User.find_by(name: params[:name])
      @user.destroy
      redirect_to root_path, success: t('.success')
    end
  end

  # フォローしている人全員
  def following
    @pagy, @users = pagy(@user.followings)
  end

  # フォロワー全員
  def follower
    @pagy, @users = pagy(@user.followers)
  end

  # ransackを使って検索したユーザーを@qに入れている
  # ユーザー検索の結果
  def search
    @q = User.search(search_params)
    @pagy, @users = pagy(@q.result(distinct: true))
  end

  private

  # パラメーターで送ることができるカラムの情報
  def user_params
    params.require(:user).permit(:nickname, :name, :password, :password_confirmation, :email, :color)
  end

  # ユーザー検索で受け取ることができるカラムの情報
  def search_params
    params.require(:q).permit(:name_cont)
  end

  def set_user
    # 　@user = User.find(params[:user_id])
    # userのnemeをパラメータで取得してユーザーを指定する
    @user = User.find_by(name: params[:user_name])
  end
end

app/views/users/follower.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row justify-content-center">
    <div class="follow-relation col-12 col-md-10 text-center">
      
      <h2 class="result"><%= @user.nickname %> followers</h2>
      
      <% if @users.empty? %>
        <div class="card no-follow">
          <div class="card-body text-center">
            <p class="follow_text">フォロワーがいません。</p>
          </div>
        </div>
      <% else %>
        <div class="row justify-content-center">
          <div class="col-md-8 col-lg-6">
            <table class="result-table table table-borderless">

            <tbody>
              <% @users.each do |user| %>
                <tr class="result text-left">
                  <td style="width: 50%">
                    <%= link_to user_diaries_path(user), class: "result-link" do%>
                      <%= user.nickname %> <%= user.name %>
                    <% end %>
                  </td>
                  <td class="text-right" style="width: 50%">
                    <% if logged_in? && current_user != user %>
                      <%= render 'relationships/follow_button_area', user: user %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
            </table>
              <div class="row justify-content-center">
                <%== pagy_bootstrap_nav(@pagy) %>
              </div>
          </div>
        </div>
      <% end %>
      <div class="text-center">
        <%= link_to 'back', user_diaries_path(@user.name), class: "btn btn-normal" %>
      </div>
    </div>
  </div>
</div>

<%= link_to "write diary", new_user_diary_path(current_user.name), class: "btn-circle-border" %>

app/views/users/following.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row justify-content-center">
    <div class="follow-relation col-12 col-md-10 text-center">

      <h2 class="result"><%= @user.nickname %> followings</h2>
      
      <% if @users.empty? && current_user == @user %>

        <div class="card no-follow">
          <div class="card-body text-center">
            <p class="follow_text">まだフォローしている人がいません。<br>
            友達を検索してフォローしませんか？</p>
            <%= link_to 'search friends', users_path, class: 'btn-show-back' %>
          </div>
        </div>
      <% elsif @users.empty? %>
        <div class="card">
          <div class="card-body text-center">
            <p class="follow_text">まだフォローしている人がいません。
          </div>
        </div>
      <% else %>
        <div class="row justify-content-center" id="contents">
          <div class="col-md-8 col-lg-6 content">
            <table class="result-table table table-borderless">
              <tbody>
                <% @users.each do |user| %>
                  <tr class="result text-left">
                    <td style="width: 50%">
                      <%= link_to user_diaries_path(user), class: "result-link" do%>
                        <%= user.nickname %> <%= user.name %>
                      <% end %>
                    </td>
                    <td class="text-right" style="width: 50%">
                      <% if logged_in? && current_user != user %>
                        <%= render 'relationships/follow_button_area', user: user %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="row justify-content-center">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="text-center">
        <%= link_to 'back', user_diaries_path(@user.name), class: "btn btn-normal" %>
      </div>
    </div>
  </div>
</div>

<%= link_to "write diary", new_user_diary_path(current_user.name), class: "btn-circle-border" %>

app/views/users/index.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row justify-content-center">
    <div class="searching col-10">
      <h1 class="search text-center"><%= current_user.nickname %> search</h1>
      <div class="text-center">
        <%= search_form_for @q, url: search_path do |f| %>
          <%= f.search_field :name_cont, placeholder: 'user name', required: true %>
          <%= f.submit t('defaults.search'), class: 'btn-show-back' %>
        <% end %>
        <p class="follow_text">ユーザー名を入力して検索します。</p>
      </div>
    </div>
  </div>
</div>

<%= link_to "write diary", new_user_diary_path(current_user.name), class: "btn-circle-border" %>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row justify-content-center">
    <div class="card resulting col-10 col-md-6">
      
      <div class="card-body">
        <h2 class="result card-title text-center">📖 <%= t '.title' %></h2>
        <div class="register">
        <%= simple_form_for @user, local: true do |f| %>
          <div class="form-group">
            <%= f.input :name, class: 'form-control', placeholder: 'emory123', hint: "半角英数字のみ使用できます" %>
          </div>
          <div class="form-group">
            <%= f.input :email, class: 'form-control', placeholder: 'emory@example.com' %>
          </div>
          <div class="form-group">
            <%= f.input :password, class: "form-control", placeholder: 'password', hint: "半角英数字8文字以上で入力してください" %>
          </div>
          <div class="form-group">
            <%= f.input :password_confirmation, class: "form-control", placeholder: 'password' %>
          </div>
          <div class="form-group">
            <%= f.input :color, as: :select, selected: 'pink', collection: User.colors.keys, class: "form-control", hint: "マイページのテーマカラーを選択してください" %>
          </div>
          <div class="text-center">
            <%= f.button :submit, t('defaults.register'), class: 'btn-normal' %>
          </div>
        <% end %>
        <div class='text-center'>
          <%= link_to t('.to_login_page'), login_path, class: "login-link" %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row justify-content-center">
    <div class="follow-relation col-12 col-md-10 text-center">
      <h2 class="result"><%= current_user.nickname %> result</h2>
      
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
        <table class="result-table table table-borderless">

          <tbody>
            <% if @users.empty? %>
              <div class="card no-follow">
                <div class="card-body text-center">
                  <p class="follow_text">検索結果がありません。<br>
                    入力を間違えていませんか？<br>
                    もう一度検索してみましょう。</p>
                  <%= link_to 'search friends', users_path, class: 'btn-show-back' %>
                </div>
              </div>
            <% else %>
            <% @users.each do |user| %>
              <tr class="result text-left">
                <td style="width: 50%">
                  <%= link_to user_diaries_path(user), class: "result-link" do%>
                    <%= user.nickname %> <%= user.name %>
                  <% end %>
                </td>
                <td class="text-right" style="width: 50%">
                  <% if logged_in? && current_user != user %>
                    <%= render 'relationships/follow_button_area', user: user %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            <% end %>
          </tbody>

        </table>
          <div class="row justify-content-center">
            <%== pagy_bootstrap_nav(@pagy) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to "write diary", new_user_diary_path(current_user.name), class: "btn-circle-border" %>