config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tops#home'
  get 'privacy', to: 'tops#privacy'
  get 'uses', to: 'tops#uses'
  get 'line', to: 'tops#line'
  get 'index', to: 'tops#index'

  # ユーザーのパスには:nameが入るようにしてあります
  resources :users, param: :name, only: %i[new create index destroy] do
    resources :followers, only: [:index]

    get 'following', to: 'users#following'
    get 'follower', to: 'users#follower'

    resources :diaries
  end

  resources :relationships, only: %i[create destroy]

  resources :bookmarks, only: %i[create destroy]

  # profiles_path, edit_profiles_path
  resource :profiles, only: %i[show edit update]

  # login_path
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  # logout_path
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  get 'search', to: 'users#search'

  # linebot
  post '/callback', to: 'linebot#callback'

  resources :password_resets, only: %i[new create edit update]

  resources :contacts, only: %i[new create]

  post 'guest', to: 'guest_sessions#create'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light fixed-top", id="header"> 
    <%= link_to root_path, class: "navbar-brand cp_link" do %>
      <img src="<%= asset_pack_path 'media/images/emory_pink.jpg' %>" >
    <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto align-items-center main-nav">
    <li class='nav-item'>
      <%= link_to t('defaults.login'), login_path, class: 'nav-link cp_link' %>
    </li>
    <li class='nav-item'>
      <%= link_to t('defaults.register'), new_user_path, class: 'nav-link cp_link' %>
    </li>
    </ul>
    </nav>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer'>
  <div class='container'>
    <div class='row'>
      <div class='col-12 text-center'>
      <p class="copyright"><%= link_to "お問い合わせ", new_contact_path, class: "copylight-link" %> | <%= link_to "利用規約", uses_path, class: "copylight-link" %> | <%= link_to "プライバシーポリシー", privacy_path, class: "copylight-link" %>
      <br>© 2021 emory</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light fixed-top", id="header">
    <% if !logged_in? || (current_user.color == "pink") %>
      <%= link_to root_path, class: "navbar-brand cp_link" do %>
        <img src="<%= asset_pack_path 'media/images/emory_pink.jpg' %>" >
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand cp_link" do %>
        <img src="<%= asset_pack_path 'media/images/emory_blue.jpg' %>" >
      <% end %>
    <% end %>
      <button class="navbar-toggler" data-toggle="collapse" data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="navbar-collapse collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class='nav-item ml-2'>
          <%= link_to t('defaults.mine'), user_diaries_path(current_user.name), class: 'nav-link cp_link' %>
        </li>
        <li class='nav-item ml-2'>
          <%= link_to t('defaults.friends_diary'), user_followers_path(current_user.name), class: 'nav-link cp_link' %>
        </li>
        <li class='nav-item ml-2'>
          <%= link_to t('defaults.search'), users_path, class: 'nav-link cp_link' %>
        </li>
        <li class='nav-item ml-2'>
          <%= link_to t('defaults.logout'), logout_path, method: :delete, data: { confirm: "<i class='fa fa-exclamation-circle'></i>
          ログアウトしますか?", commit: 'logout', cancel: 'cancel' }, class: 'nav-link cp_link' %>
        </li>
        <li class='nav-item ml-2'>
          <%= link_to current_user.nickname, profiles_path, class: 'nav-link cp_link' %>
        </li>
        <li class='nav-item ml-2'>
        <%= link_to line_path, class: "flowbtn10", remote: true, :data => {:toggle=>"modal", :target => "#lineModal", :backdrop => "true"} do %>
          <i class="fab fa-line"></i>
        <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

<div class="modal fade" id="lineModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
	  <div class="modal-content"></div>
  </div>
</div>